#!/bin/bash

cmdline="
--fg-root=/usr/local/FlightGear
--aircraft=OV10
--airport-id=KSFO
--geometry=1024x768
--prop:/consumables/fuel/tank[0]/level-gal_us=117
--prop:/consumables/fuel/tank[1]/level-gal_us=117
--prop:/consumables/fuel/tank[2]/level-gal_us=220
--prop:/engines/engine[0]/running=true
--prop:/engines/engine[1]/running=true
--prop:/instrumentation/marker-beacon/audio-btn[0]=false
--prop:/instrumentation/nav/frequencies/selected-mhz[0]=111.7
--prop:/instrumentation/nav/radials/selected-deg[0]=283.0
--prop:/instrumentation/nav[1]/frequencies/selected-mhz[0]=115.8
--prop:/instrumentation/dme/switch-position=1
--prop:/instrumentation/attitude-indicator/config/tumble-flag=false
--visibility-miles=4.0
--enable-sound
--disable-clouds
--disable-hud
--start-date-gmt=2003:01:20:16:00:00
"

fgfs $cmdline
exit 0

